joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0


# configuration for Logitech Extreme 3D Pro
teleop_node:
  ros__parameters:
    axis_linear:
      y: 0
      x: 1
      z: 3
    scale_linear:
      y: 0.6
      x: 0.6
      z: 0.6
    scale_linear_turbo:
      y: 1.0
      x: 1.0
      z: 1.0

    axis_angular:
      yaw: 2
      pitch: 5
      roll: 4
    scale_angular:
      yaw: 0.8
      pitch: 0.8
      roll: -0.8
    scale_angular_turbo:
      yaw: 1.0
      pitch: 1.0
      roll: -1.0


    enable_button: 10
    enable_turbo_button: 1

    require_enable_button: false #enables "Deadman" of the enable button