controller_manager:
  ros__parameters:
    update_rate: 20 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController



forward_position_controller:
  ros__parameters:
    joints: 
      - first_arm_yaw
      - first_arm_pitch
      - first_knee_joint
      - second_arm_yaw
      - second_arm_pitch
      - second_knee_joint
      - third_arm_yaw
      - third_arm_pitch
      - third_knee_joint
      - fourth_arm_yaw
      - fourth_arm_pitch
      - fourth_knee_joint

    interface_name: position


joint_trajectory_controller:
  ros__parameters:
    joints:
      - first_arm_yaw
      - first_arm_pitch
      - first_knee_joint
      - second_arm_yaw
      - second_arm_pitch
      - second_knee_joint
      - third_arm_yaw
      - third_arm_pitch
      - third_knee_joint
      - fourth_arm_yaw
      - fourth_arm_pitch
      - fourth_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)


# joint_broad:
#   ros__parameters: